# Generated by Django 2.2.16 on 2024-10-30 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 39, 49, 82021))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 39, 49, 82057))),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpDeskProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk', to='ticket.Ticket')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
