# Generated by Django 2.2.16 on 2024-10-30 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20241030_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 46, 22, 385300)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 13, 46, 22, 385273)),
        ),
    ]
